image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}.$CI_COMMIT_SHORT_SHA

stages:
  - test
  - build
  - deploy

code-quality:
 stage: test
 image: docker:stable
 allow_failure: true
 services:
   - docker:stable-dind
 variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2
 script:
   - >
     docker run --env SOURCE_CODE="$PWD"
     --volume "$PWD":/code
     --volume /var/run/docker.sock:/var/run/docker.sock
     "registry.gitlab.com/gitlab-org/security-products/codequality" /code
 artifacts:
     paths: [gl-code-quality-report.json]
 except:
   - master

docker-build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker info
    - docker push $DOCKER_IMAGE_TAG

k8s-deploy-staging:
  stage: deploy
  variables:
    DEPLOY_SUFFIX: staging
  environment:
    name: staging
  image: devth/helm
  script:
    - helm init
    - helm repo update
    - cat chart/values.yaml | envsubst | helm upgrade ./charts --name pangaeanodejs-staging --namespace staging -f ./values.yaml
  only:
    - staging

k8s-deploy-production:
  stage: deploy
  variables:
    DEPLOY_SUFFIX: production
  environment:
    name: production
  image: devth/helm
  script:
    - helm init
    - helm repo update
    - cat chart/values.yaml | envsubst | helm upgrade ./charts --name pangaeanodejs-prod --namespace production -f ./values.yaml
  when: manual
  only:
    - master
